### ISSUE TITLE
Make a nice logo for the library

### ISSUE THREAD

**Issue by yacineMahdid** [BIAPT/NeuroAlgo#24]

**Comment by dnadin** [comment]
I'd enjoy doing this if you need help :-)

**Comment by yacineMahdid** [comment]
@dnadin would be cool if you have time! I just made one for fun:
![logo](https://user-images.githubusercontent.com/28378576/84841930-d0121500-b011-11ea-923d-037b67ed2d77.png)

If you have a better idea you can pitch them in here!
